kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

clone:
  depth: 50
   
steps:
- name: backend
  commands:
  - docker compose build backend

- name: cleanup
  commands:
  - docker system prune -f
  when:
    status:
      - failure
      - success
  depends_on:
    - backend

- name: deploy
  environment:
    PORT: 5000
    DB_LOCATION: "/mnt/volume_sgp1_01/countdown/db"
  commands:
    - docker compose -p countdown_staging up -d --force-recreate

trigger:
  target:
    exclude:
      - production

---
kind: pipeline
type: exec
name: deploy

steps:
  - name: deploy
    environment:
      PORT: 2000
      DB_LOCATION: "/mnt/volume_sgp1_01/countdown/production"
    commands:
    - docker compose -p countdown_production up -d --force-recreate

trigger:
  event:
  - promote
  target:
  - production
