kind: pipeline
type: exec
name: build

platform:
  os: linux
  arch: amd64

clone:
  depth: 50
   
steps:
- name: backend
  commands:
  - docker compose build backend
  -
- name: webapp
  environment:
    VITE_API_URL: /api
  commands:
    - docker compose build webapp

- name: cleanup
  commands:
  - docker system prune -f
  when:
    status:
      - failure
      - success
  depends_on:
    - backend
    - webapp

- name: deploy
  environment:
    BE_PORT: 5000
    WA_PORT: 5001
    DB_LOCATION: "/mnt/volume_sgp1_01/countdown/db"
  commands:
    - docker compose -p countdown_staging up -d --force-recreate

trigger:
  target:
    exclude:
      - production

---
kind: pipeline
type: exec
name: deploy

steps:
  - name: deploy
    environment:
      BE_PORT: 2000
      WA_PORT: 2001
      DB_LOCATION: "/mnt/volume_sgp1_01/countdown/production"
    commands:
    - docker compose -p countdown_production up -d --force-recreate

trigger:
  event:
  - promote
  target:
  - production
