services:
  backend:
    image: countdown-backend
    build:
      context: backend
    volumes:
      - ${DB_LOCATION-./db}:/home/nonroot/db
    ports:
      - "${PORT-8080}:8080"
    networks:
      - backend
  webapp:
    image: countdown-webapp
    build:
      context: webapp
    ports:
      - "${PORT-5000}:80"
    networks:
      - backend

networks:
  backend:
    name: countdown-backend
    driver: bridge
