services:
  backend:
    image: countdown-backend
    build:
      context: backend
    volumes:
      - ${DB_LOCATION-./db}:/home/nonroot/db
    ports:
      - "${PORT-8080}:8080"
  webapp:
    image: countdown-webapp
    build:
      context: webapp
      args:
        - VITE_API_URL=${VITE_API_URL-http://localhost:8080}
    ports:
      - "${PORT-5001}:80"
